// playground/integration/devToolbarPlugins/Test.react.jsx
import { useState } from 'react';

const Counter = () => {
  const [count, setCount] = useState(0);

  const increment = () => {
    setCount(count + 1);
  };

  const decrement = () => {
    setCount(count - 1);
  };

  return (
    <div>
      <h1>Counter: {count}</h1>
      <button onClick={increment}>Increment</button>
      <button onClick={decrement}>Decrement</button>
    </div>
  );
};

export default Counter;

// playground/integration/devToolbarApps/Test.solid.jsx
import { createSignal } from "solid-js";

function Counter() {
	const [count, setCount] = createSignal(1);
	const increment = () => setCount(count() + 1);

	return (
		<div>
			<h1>Count: {count()}</h1>
			<button type="button" onClick={increment}>
				Increment
			</button>
		</div>
	);
}

export default Counter;
